---
codecov:
  disable_default_path_fixes: no
  # Should CI be required to pass before uploading the report:
  # https://docs.codecov.io/docs/codecovyml-reference#section-codecov-require-ci-to-pass
  require_ci_to_pass: no
  notify:
    # Should Codecov wait for all CI statuses to complete before sending ours
    # https://docs.codecov.io/docs/codecovyml-reference#section-codecov-notify-wait-for-ci
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        # https://docs.codecov.io/docs/commit-status#section-basic-configuration
        # auto will use the coverage from the base commit (pull request base or parent
        # commit) coverage to compare against.
        target: auto
        # Allow the coverage to drop by X%, and posting a success status.
        threshold: 2%

parsers:
# Can't find documentation on this
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  # Will need after_n_builds if and when testing is performed across platforms
  # to prevent multiple builds from each triggering their own comment
  # https://docs.codecov.io/docs/pull-request-comments#section-after_n_builds
...